name: Python format and coverage

on:
  push:
    branches:
      - action-python-sample-app

jobs:
    pre-build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Lint python code
          run: ruff --output-format=github .
          continue-on-error: true
        
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Test with pytest
          run: |
              pip install pytest pytest-cov
              pytest tests/test_calculator.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
        
        - name: Upload pytest test results
          uses: actions/upload-artifact@v3
          with:
            name: pytest-results-ver1
            path: junit/test-results.xml
          if: ${{ always() }}

